apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cassandraLoadKeySpace.name }}
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ "nexus-cicd" }}
      containers:
      - name: {{ .Values.cassandraLoadKeySpace.name }}
        image: "{{ .Values.cassandraLoadKeySpace.repository }}:{{ .Values.cassandraLoadKeySpace.tag }}"
      restartPolicy: Never
  backoffLimit: 0