apiVersion: v1
kind: Service
metadata:
  name: {{ include "otk_db.fullname" . }}
  labels:
{{ include "otk_db.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: cassandra-port
      protocol: TCP
      name: cassandra-port
  selector:
    app.kubernetes.io/name: {{ include "otk_db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
